---
title: "PreId_Comparison"
author: "Leah Hale"
date: "29/04/2015"
output: html_document
---


```{r,results='asis'}

library("xtable")
source("LoadData.R");

ftable<-data.frame();

HEFCard_by_PreId <- c(sum(lps[HEFCard,]$PreId),sum(!lps[HEFCard,]$PreId));
GVTPoor_by_PreId <- c(sum(lps[GVTPoor,]$PreId),sum(!lps[GVTPoor,]$PreId));
NoInsu_by_PreId  <- c(sum(lps[NoInsu,]$PreId), sum(!lps[NoInsu,]$PreId));
            


ftable <- rbind(HEFCard_by_PreId,GVTPoor_by_PreId,NoInsu_by_PreId);

ftable<-cbind(ftable,rowSums(ftable));
rownames(ftable)<-c("HEF Card Holder","Govenment Poor List","No Insurance")
colnames(ftable)<-c("PreId","Geo","Row Total");
print(xtable(ftable),"html")

```
```{r}
source("AnalyzeGroups.R");
```

```r sum(HEF_PreID & NoAssist)``` persons are on both the HEF_PreId and the NoAssist List we will cound them as HEF.

```r sum (HEF_PreID & Geo_Poor)```

which(HEF_PreID & NoAssist)


```{r,results='hide'}
HEF_PreID <-lps$PreId & HEFCard;
Geo_Poor  <-!lps$PreId & GVTPoor;
NoAssist  <-lps$PreId & NoInsu;

lgroups <- list(HEF_PreID,Geo_Poor,NoAssist)
```

<<<<<<< HEAD
#Family size
```{r} 
wilcox.test(HH_NumPeople~HEF_PreID,data=lps[OnAList])
``` 
HEF to all in sample group.
```{r}
wilcox.test(HH_NumPeople~Geo_Poor,data=lps[OnAList])
``` 
GeoPoor to all in sample group.
```{r}
wilcox.test(HH_NumPeople~NoAssist,data=lps[OnAList])
``` 
No Assist to all in sample group.
=======
#Gender

```{r,results='asis'}
#create a blank frame to hold the table
ftable <-data.frame();
#copute the rows for each group in the table
for (l in lgroups) {
  rtab<-c(sum(lps[l,"Gender"]=="F",na.rm=TRUE),sum(lps[l,"Gender"]=="M",na.rm=TRUE))
  ftable<-cbind(ftable,rtab)
}
#ftable<-cbind(ftable,rowSums(ftable));
rownames(ftable) <- c("F","M")
colnames(ftable) <- c("HEF","GEO_Poor","NoAssist")
```

## Gender of respondents
```{r,results='asis'}
print (xtable(ftable),"html")

```
## Gender of all

#Num Peopls
```{r}
n1<-which(names(lps)=="q2_1_2_30")
vname<-!is.na(lps[,n1:(n1+29)])
nnames<-rowSums(vname)
sum (!lps$HH_NumPeople == nnames)

hist(lps$HH_NumPeople - nnames)
hist(lps$HH_NumPeople)
hist(nnames)
```
Num names matches num people every times
>>>>>>> e9ad12049f56229c53e2b97437f1e1154a0147d7
